### ISSUE TITLE
Can't build on Windows 10

### ISSUE THREAD

**Issue by Kaduo** [blas-lapack-rs/openblas-src#28] opened 2019-04-19 09:41 UTC
When trying to build the crate with cargo, I get the following error messsage : 

```powershell
error: failed to run custom build command for `openblas-src v0.7.0`
process didn't exit successfully: `C:\Users\(...)\target\debug\build\openblas-src-ea19b54cda88a9a7\build-script-build` (exit code: 101)
--- stdout
Running: `"cp" "-R" "source" "source_x86_64-pc-windows-msvc_tmp"`

--- stderr
thread 'main' panicked at 'Failed: `"cp" "-R" "source" "source_x86_64-pc-windows-msvc_tmp"` (The file can't be found. (os error 2))', C:\Users\(...)\.cargo\registry\src\github.com-1ecc6299db9ec823\openblas-src-0.7.0\build.rs:72:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I am using the latest stable version of rust (1.34.0) on Windows 10.

**Comment by Kaduo** [comment] 2019-04-19 12:05
After some toying around, the issue seems to be that the windows shell doesn't have a "cp" command, or a "make" command for that matter, so the shell thinks that these are local executables, hence the "unknown file" error. I'm not sure what I can do to circumvent this issue...

**Comment by IvanUkhov** [comment] 2019-04-19 17:09
Yes, I suspected that. Unfortunately, the build script was not written with Windows in mind. Some help from an experienced Windows user is required in order to make appropriate adjustments.

**Comment by VanioBegic** [comment] 2019-06-01 12:34
Actually both make and cp commands are functional in windows powershell uf you have gnu make and cygwin installed and on path. Though the commands are functional on my shell, I too get the same error but mine is formatted bit differently to "source_x86_64-pc-windows-msvc-tmp". I hope this can be resolved as I am unable to use linux on my system.

**Comment by IvanUkhov** [comment] 2019-06-01 13:41
For those interested in researching into the root cause, I’ve set up AppVeyor. Here one can see how it fails for four different configurations with two different errors:

https://ci.appveyor.com/project/IvanUkhov/openblas-src

**Comment by VanioBegic** [comment] 2019-06-01 21:48
Changing make to cmake and cp -R command to robocopy source source_x86_64-pc-windows-gnu_tmp /e I get following result for Environment: TARGET=x86_64-pc-windows-msvc https://ci.appveyor.com/project/VanioBegic/openblas-src/builds/24976367/job/2adrcsyx4vaj4yt3 .

The exit code is 1 in this case, which seems to be the problem, since usually anything but 0 is interpreted as error, and I do not know if this is also a case with Rust Command

**Comment by IvanUkhov** [comment] 2019-06-02 05:52
Thank you for looking into this! Yes, the actual problem is the following:

```
thread 'main' panicked at 'Failed: `"robocopy" "source" "source_x86_64-pc-windows-msvc_tmp" "/e"` (exit code: 1)', build.rs:68:17
```

In other words, this `rotocopy` command returned a nonzero status, and hence everything failed. By changing the `run` function the say you did, you let this error be ignored.

Since you got to the linking part, does it mean that you were able to compile OpenBLAS? The whole process should take 10–20 minutes. If it finished in a few seconds, it probably didn’t go well.

In any case, I think the best way to make it work is to compile OpenBLAS in isolation first. That is, just clone their repository and try to go through the whole process from start to finish manually. Then it’ll be a matter of reproducing the same commands in the build script, assuming that all requirements are installed. Here are some instructions:

https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio

**Comment by VanioBegic** [comment] 2019-06-02 07:58
As said, this is actually not an error. Robocopy returns exit code 1, when it successfully copies all files. But directly afterwards it returns with note: LINK : fatal error LNK1181: cannot open input file 'gfortran.lib' 

I will try to follow the tutorial given in the link above, and will come back with results.

**Comment by IvanUkhov** [comment] 2019-06-02 08:12
Yes, you are right:

https://blogs.technet.microsoft.com/deploymentguys/2008/06/16/robocopy-exit-codes/

**Comment by VanioBegic** [comment] 2019-06-02 08:17
Now when I clone the repository and build OpenBLAS manually, how do I link it to rust? Root cause of my problem is actually that I am trying to use ndarray-linalg library, but none of the BLAS crates compiles, and this one seemed most promising. Any tutorials would be helpful.

**Comment by IvanUkhov** [comment] 2019-06-02 08:24
So now you’re able to compile it manually, right? Then the natural next step is to integrate it into this crate and make the [test](https://github.com/blas-lapack-rs/openblas-src/blob/master/tests/lib.rs) here pass. In theory, the only thing that is needed is to link everything properly. You have the library compiled, and now tell Rust to use it in the build script.

1. [Change `cargo:rustc-link-search` to point to the folder with the library.](https://github.com/blas-lapack-rs/openblas-src/blob/master/build.rs#L54)
2. [Remove redundant libraries.](https://github.com/blas-lapack-rs/openblas-src/blob/master/build.rs#L59)
3. [Tell it the name of the library to take.](https://github.com/blas-lapack-rs/openblas-src/blob/master/build.rs#L60)

**Comment by VanioBegic** [comment] 2019-06-03 06:13
So I made some progress on my machine here are the steps I took: 

1. From [https://github.com/msys2/msys2/wiki/MSYS2-installation](this guide) install MSYS2 for your system
2. ALL THE FOLLOWING STEPS PROCEED FROM MSYS SHELL
3. Open MSYS shell
4. Run `pacman -S gcc pacman -S make pacman -S gcc-fortran pacman -S git`
5. Run `git clone https://github.com/xianyi/OpenBLAS`
6. Run `cd OpenBLAS`
7. Run `make`
8. Run `make install`

Now after these steps the .a files can be usually found under C:\msys64\opt\OpenBLAS\lib if the installation of MSYS proceeded as given in link.  Now if one wants to use this build of OpenBLAS for openblas-src it is necesarry to remove all calls to make from build script, and make corrections for robocopy on windows systems as discussed in previous comments.

Now it is the matter of translating these steps into build-script.

**Comment by IvanUkhov** [comment] 2019-06-03 06:40
Perfect! Have you tried to hard-code your manual installation in the build script to check if it is actually able to find and use what is needed? I also assume that all the different parameters that we pass to `make` in the build script (`BINARY`, `{YES,NO}_CBLAS`, `{YES,NO}_LAPACKE`, and `DESTDIR`) continue to work properly. Plus the `libs`, `netlib`, and `shared` should still exist. I suppose there should be no major difference; it’s the same `Makefile` that is used.

Assuming the above is the case, I’d proceed as follows. All the prerequisites should be assumed to be installed. We shouldn’t try to do any in this regard the build script. It’s better to write it in the [Wiki](https://github.com/blas-lapack-rs/blas-lapack-rs.github.io/wiki) and then make sure people can find it from every package. Then the only thing that has to be changed is the copying of the `source` directory to a target-specific folder. According to your findings, we have to have two versions of this operation: one for `#[cfg(unix)]` and one for `#[cfg(windows)]`. Then one has to extract it into a separate function. Alternatively, one has to write this bit in pure Rust.

What do you think?

**Comment by VanioBegic** [comment] 2019-06-03 08:51
Comically enought now cargo build runs to end, but cargo test fails because it cant find a gfortran.lib file, which is not even present on my computer. Even when I comment out the specific println it still fails because it can not find openblas.lib file, which is sadly enough also not present on my computer. I am trying to resolve the issue by trying gnu toolchain.

**Comment by IvanUkhov** [comment] 2019-06-03 08:55
Do you not get `gfortran.lib` installed when you run `pacman -S gcc-fortran`? What does `make` compile if not `openblas.lib`? I’d expect this library to be found after `make libs netlib shared`.

**Comment by VanioBegic** [comment] 2019-06-03 09:42
Actually I do not get gfortran.lib file after running pacman -S gcc-fortran on msys2. What I do get is libgfortran.a and libgfortran.dll.a files located at C:\msys64\usr\lib\gcc\x86_64-pc-msys\7.4.0 

About openblas.lib I can not confirm nor deny it, since I did not run `make libs netlib shared` as used in build script but rather `make` as described on the OpenBLAS page which you linked to earlier. 

Update:
Right now I recompiled the OpenBLAS with `make libs netlib shared` and got following output after long compilation text : 

`ranlib ../../../cygopenblas_haswellp-r0.3.7.dev.a
make[3]: Leaving directory '/d/OpenBLAS/lapack-netlib/LAPACKE/utils'
make[2]: Leaving directory '/d/OpenBLAS/lapack-netlib/LAPACKE'
make[1]: Leaving directory '/d/OpenBLAS/lapack-netlib'
make[1]: warning: -jN forced in submake: disabling jobserver mode.
make[1]: Entering directory '/d/OpenBLAS/exports'
perl ./gensymbol win2k    x86_64 dummy 0 0 0 0 0 0 "" "" 1 > cygopenblas.def
cc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=2 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.7.dev\" -mavx2 -DASMNAME=dllinit -DASMFNAME=dllinit_ -DNAME=dllinit_ -DCNAME=dllinit -DCHAR_NAME=\"dllinit_\" -DCHAR_CNAME=\"dllinit\" -DNO_AFFINITY -I.. -c -o dllinit.o -s dllinit.c
ranlib ../cygopenblas_haswellp-r0.3.7.dev.a
cc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=2 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.7.dev\" -mavx2 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  cygopenblas.def dllinit.o \
-shared -o ../cygopenblas.dll -Wl,--out-implib,../libopenblas.dll.a \
-Wl,--whole-archive ../cygopenblas_haswellp-r0.3.7.dev.a -Wl,--no-whole-archive -L/usr/lib/gcc/x86_64-pc-msys/7.4.0 -L/usr/lib/gcc/x86_64-pc-msys/7.4.0/../../../../x86_64-pc-msys/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-pc-msys/7.4.0/../../../../x86_64-pc-msys/lib -L/usr/lib/w32api  -lgfortran -lquadmath -lm -lmsys-2.0   -lgfortran -lgfortran
make[1]: Leaving directory '/d/OpenBLAS/exports'
`

When I run make install I still get no openblas.lib but rather I get cygopenblas.a and cygopenblas.dll and libopenblas.dll.a files in C:\msys64\opt\OpenBLAS\bin.

In most recent attempt I am trying to compile this repo directly from msys.

**Comment by IvanUkhov** [comment] 2019-06-03 10:01
It’s good news that you have `libgfortran.a`, `libgfortran.dll.a`, `cygopenblas.a`, `cygopenblas.dll`, and `libopenblas.dll.a`. Those that end with `.a` are for static linking (see the `static` Cargo feature in the build script). The one that ends with `.dll` is for dynamic. The question is, what those ending with `*.dll.a` are for? Maybe they are the one needed for dynamic linking but named differently for some reason. Here we need a Windows expert. Perhaps `rustc` can pick it up automatically? Not sure where the `.lib` convention comes from, and how to influence it.

I’d simplify the build script by hard-coding the path to your manual installation and then play with different linking options.

https://doc.rust-lang.org/cargo/reference/build-scripts.html

**Comment by VanioBegic** [comment] 2019-06-03 10:23
It compiles with original build script from MSYS2 shell . I guess we can close the issue, and write in readme or wiki that compilation on windows must be done through MSYS2 shell rather then powershell.

**Comment by IvanUkhov** [comment] 2019-06-03 10:35
How come nothing is passing on AppVeyor then?

https://ci.appveyor.com/project/IvanUkhov/openblas-src

Do you know how the configuration file has to be adjusted to make it work?

https://github.com/blas-lapack-rs/openblas-src/blob/master/appveyor.yml

**Comment by VanioBegic** [comment] 2019-06-03 11:06
The shell is different. Basically one needs to start this special shell which is installed together with MSYS2 called MSYS2 MinGW 64-bit ( in case of 64 bit enviroment, and 32 bit in case of 32 bit enviroment ) , and then run all the arguments from there. Seems like the way to make that happen in Rust is outlined in following : https://stackoverflow.com/questions/29903129/invoking-shell-scripts-on-windows-under-msys-using-command

**Comment by IvanUkhov** [comment] 2019-06-05 11:03
@VanioBegic, I’ve [tried doing it from `sh`](https://github.com/blas-lapack-rs/openblas-src/blob/master/appveyor.yml#L23), which is shipped with MSYS if I’m not mistaken, but it [didn’t seem to help](https://ci.appveyor.com/project/IvanUkhov/openblas-src/builds/25021577). One has to make `rustc` be able to find `gfortran`. How did you do this?

**Comment by VanioBegic** [comment] 2019-06-05 11:18
@IvanUkhov As long as you keep getting errors, it is an indicator that a package is not installed in MSYS enviroment. The -lgfortran error is caused because you lack mingw-w64-x86_64-gcc-libgfortran and you can install it by running `pacman -S mingw-w64-x86_64-gcc-libgfortran` in case that you are using MinGW enviroment, and if that does not run, then run `pacman -Ss gfortran` to find a lib that you can install. Once installed the -lgfortran error goes away.

**Comment by IvanUkhov** [comment] 2020-08-29 16:55
I close this due to the recent development.

**Closed by IvanUkhov** 2020-08-29 16:55 UTC
Labels: help wanted, windows
